name: plant_care_reminder_app
description: A plant care reminder application to help users maintain their plants.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # State management
  provider: ^6.1.1

  # UI packages
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Image handling
  image_picker: ^1.0.5
  photo_view: ^0.15.0

  # Location and Weather
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  weather: ^3.1.1

  # Local storage
  shared_preferences: ^2.3.3
  sqflite: ^2.3.0
  path: ^1.8.3

  # Date and time
  intl: ^0.20.2

  # Utilities
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.3
  url_launcher: ^6.2.2
  http: ^1.2.2

  #dotenv:
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true
  assets:
    - .env