// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['APIKEY_WEB'] ?? '',
    appId: dotenv.env['APPID_WEB'] ?? '',
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID_WEB'] ?? '',
    projectId: dotenv.env['PROJECT_ID_WEB'] ?? '',
    authDomain: dotenv.env['AUTH_DOMAIN_WEB'] ?? '',
    storageBucket: dotenv.env['STORAGE_BUCKET_WEB'] ?? '',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['APIKEY_ANDROID'] ?? '',
    appId: dotenv.env['APPID_ANDROID'] ?? '',
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID_ANDROID'] ?? '',
    projectId: dotenv.env['PROJECT_ID_ANDROID'] ?? '',
    storageBucket: dotenv.env['STORAGE_BUCKET_ANDROID'] ?? '',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['APIKEY_IOS'] ?? '',
    appId: dotenv.env['APPID_IOS'] ?? '',
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID_IOS'] ?? '',
    projectId: dotenv.env['PROJECT_ID_IOS'] ?? '',
    storageBucket: dotenv.env['STORAGE_BUCKET_IOS'] ?? '',
    iosBundleId: dotenv.env['IOS_BUNDLE_ID'] ?? '',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['APIKEY_MACOS'] ?? '',
    appId: dotenv.env['APPID_MACOS'] ?? '',
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID_MACOS'] ?? '',
    projectId: dotenv.env['PROJECT_ID_MACOS'] ?? '',
    storageBucket: dotenv.env['STORAGE_BUCKET_MACOS'] ?? '',
    iosBundleId: dotenv.env['MACOS_BUNDLE_ID'] ?? '',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['APIKEY_WINDOWS'] ?? '',
    appId: dotenv.env['APPID_WINDOWS'] ?? '',
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID_WINDOWS'] ?? '',
    projectId: dotenv.env['PROJECT_ID_WINDOWS'] ?? '',
    authDomain: dotenv.env['AUTH_DOMAIN_WINDOWS'] ?? '',
    storageBucket: dotenv.env['STORAGE_BUCKET_WINDOWS'] ?? '',
  );
}
